version: '3.3'

networks:
  traefik:
    external: true

services:
  post-job:
    container_name: post-job
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
    ports:
      - "8000:8000"