ultramsg:
  baseUrl: https://api.ultramsg.com/INSTANCIA_ID
  image: /messages/image
  token: TOKEN_APP

spring:
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 100000
        ok-http:
          read-timeout: 200000
