gowhats:
  baseUrl: https://whatsapp.mmtechnology.com.br
  image: /client/sendMessage
  token: WHATSAPPKEY

spring:
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 100000
        ok-http:
          read-timeout: 200000

feign:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000